#!/bin/bash
# push a biograph release to Docker Hub

if [ -z "$1" ]; then
	echo "Usage: $(basename $0) [biograph version]"
	exit 1
fi

export VERSION=$1

if [ "$(docker images biograph-${VERSION}:latest|wc -l)" != "2" ]; then
	echo "No docker image exists for biograph-${VERSION}. Run 'prepare_container' first."
	exit 1
fi

set -e

docker login

docker tag biograph-${VERSION}:latest spiralgenetics/biograph:biograph-${VERSION}
docker tag biograph-${VERSION}:latest spiralgenetics/biograph:latest
docker push spiralgenetics/biograph:biograph-${VERSION}
docker push spiralgenetics/biograph:latest
