#!/bin/bash
set -e
. versions.bzl

if ! git diff-index --quiet HEAD --; then
	echo $'\nYou have uncommitted local changes. Cannot continue.\n'
	git status
	exit 1
fi

REV=$(git rev-parse --short HEAD)

DEST="s3://spiral-releases/dev/BioGraph-${BIOGRAPH_VERSION}-${REV}.tgz"

bazel build -c opt //python/biograph:package

echo
echo "Hit enter to push your dev build to ${DEST}, or ^C to cancel."
read

aws s3 cp bazel-bin/python/biograph/BioGraph-${BIOGRAPH_VERSION}.tgz ${DEST}

echo
echo "Pushed to: ${DEST}"
